#!/bin/bash

cp $PBS_O_WORKDIR/* $TMPDIR
cd $TMPDIR
for i in `ls testgrid*`; do echo -e "\n\n======================"; basename $i; echo "======================"; time ./persistent 0.02 0.02 8 < $i; done 2>&1 | tee presults.txt;
    
cp presults.txt $PBS_O_WORKDIR
