#!/bin/bash

cp $PBS_O_WORKDIR/* $TMPDIR
cd $TMPDIR
for i in {1..12}; do echo -e "\n\n============ Total Num Threads $i ================"; time ./persistent 0.02 0.02 $i < testgrid_400_12206; done 2>&1 | tee ptresults_10.txt;
#for i in {1..5}; do echo -e "\n\n============ Total Num Threads $i ================"; time ./persistent 0.02 0.02 $i < testgrid_400_12206; done 2>&1 | tee ptresults1-5.txt &;
#for i in {6..10}; do echo -e "\n\n============ Total Num Threads $i ================"; time ./persistent 0.02 0.02 $i < testgrid_400_12206; done 2>&1 | tee ptresults6-10.txt &;
#for i in {11..15}; do echo -e "\n\n============ Total Num Threads $i ================"; time ./persistent 0.02 0.02 $i < testgrid_400_12206; done 2>&1 | tee ptresults11-15.txt &;
#for i in {16..20}; do echo -e "\n\n============ Total Num Threads $i ================"; time ./persistent 0.02 0.02 $i < testgrid_400_12206; done 2>&1 | tee ptresults16-20.txt &;
#for i in {21..23}; do echo -e "\n\n============ Total Num Threads $i ================"; time ./persistent 0.02 0.02 $i < testgrid_400_12206; done 2>&1 | tee ptresults21-23.txt &;
#for i in {23..25}; do echo -e "\n\n============ Total Num Threads $i ================"; time ./persistent 0.02 0.02 $i < testgrid_400_12206; done 2>&1 | tee ptresults23-25.txt &;
#for i in {26..28}; do echo -e "\n\n============ Total Num Threads $i ================"; time ./persistent 0.02 0.02 $i < testgrid_400_12206; done 2>&1 | tee ptresults26-28.txt &;
    
cp ptresults_10.txt $PBS_O_WORKDIR
